### ISSUE TITLE
Start release some versions

### ISSUE THREAD

**Issue by clemens-tolboom** [clue/graph-uml#22]
As asked for in #13 I'd like to have some pinned versions.

This makes working on a stable Graph API module for Drupal. I'm currently feel chasing herrings :-/

Creating a branch is probably a bridge to far and could drain progress on this project.

We could start with v0.x.y similar to graph but now having an incrementing y at will of one of the developers.

@clue what do you think?

**Comment by clue** [comment]
Makes perfect sense! I'll look into tagging some alpha releases from the history.

**Comment by clue** [comment]
v0.1.0 and v0.2.0 have just been released.

**Comment by clemens-tolboom** [comment]
Thanks
