### ISSUE TITLE
Define an abstract record structure

### ISSUE THREAD

**Issue by clemens-tolboom** [clue/graph-uml#23]
I think it would be nice to allow not only graphviz to use our UML data.

The transformation of our labels into #5 HTML like text is a post processing phase. Only needed for the dot language.

Other tools like thejit, d3js or graph_phyz allow for other table-like structures.

**Comment by clemens-tolboom** [comment]
I added a milestone to see how that works too.

Would the DOMDocument fill our needs as it's a tree with attributes.

**Comment by clue** [comment]
Thanks, certainly makes sense to track this a as dedicated ticket.

> Would the DOMDocument fill our needs as it's a tree with attributes.

I'd rather not introduce that dependency. I'll see what I can come up with.

**Comment by clemens-tolboom** [comment]
I understand your hesitation for dependencies. But the other side is writing your own code.

Is https://github.com/nicmart/Tree useful?

**Comment by clemens-tolboom** [comment]
There exists http://www.php.net/manual/en/class.recursiveiterator.php which helps some I guess.

**Comment by clue** [comment]
I'm not sure I get the motivation for this change, perhaps you can elaborate? What kind of information does this "record structure" hold that can not be seen by plain reflection?

I understand that exports to other formats _could_ be nice, but I'm unsure if this worth the hassle tbh.

**Comment by clemens-tolboom** [comment]
Not sure now :( ... won't fix?

**Comment by clue** [comment]
Alright, let's close this one until we find a good reason to reopen :-)
