### ISSUE TITLE
Dependency Problem while composer installing

### ISSUE THREAD

**Issue by metalmatze** [clue/graph-uml#27]
```
Problem 1
- Installation request for clue/graph-uml dev-master -> satisfiable by clue/graph-uml[dev-master].
- clue/graph-uml dev-master requires clue/graph dev-master -> no matching package found.
```

**Comment by metalmatze** [comment]
Oh. Just found out that my composer.json missed `"minimum-stability": "dev"`.
That has resolved the problem.

**Comment by clue** [comment]
> That has resolved the problem.

Thanks for sharing your findings though! Once #22 is done, this should no longer be necessary.
