### ISSUE TITLE
SVG Rendering on Chrome fails to render some text properly

### ISSUE THREAD

**Issue by clemens-tolboom** [clue/graph-uml#28]
All type like `«interface»` is rendered like `Â«interfaceÂ»`

![accesscheckinterface___accesscheckinterface_php___drupal_8_x___api_dev_voorbeeld-site_nl_and_accesscheckinterface___accesscheckinterface_php___drupal_8_x___api_dev_voorbeeld-site_nl-4](https://f.cloud.github.com/assets/371014/2230009/5db49f8e-9af9-11e3-8406-66809d147d8e.png)

**Comment by clemens-tolboom** [comment]
According to sysosmaster @ irc this relates to https://productforums.google.com/forum/#!topic/chrome/8XLAYGfZ-Ws

Not sure though.

**Comment by clue** [comment]
Is this still an issue?

If so, what can we do about this? Perhaps avoid unicode characters and use plain ASCII replacements via a config?

**Comment by clemens-tolboom** [comment]
Dunno .. I am quite deviated from Graphs and even Drupal doing VR :-)

**Comment by clue** [comment]
Fixed via https://github.com/graphp/graphviz/pull/27 :shipit:
