### ISSUE TITLE
Add graph-uml to packagist

### ISSUE THREAD

**Issue by clemens-tolboom** [clue/graph-uml#6]
I just tried a `composer init` which failed to find graph-uml.

We should add this to https://packagist.org

**Comment by clue** [comment]
Yeah, kind of lost track of this repo. Sorry.

I'm tempted to move it back to clue/graph-uml and release it as such. Any thoughts?

**Comment by clemens-tolboom** [comment]
I have no clue (pun intended) what is best. My contribs are minimal so fhaculty seems not to be very useful.

It's no problem to me to revert this back to clue/graph-uml so yes let's shutdown Fhaculty. :+1:

**Comment by clue** [comment]
Done :)

https://packagist.org/packages/clue/graph-uml

**Comment by clemens-tolboom** [comment]
thanks
